### ISSUE TITLE
Outbound scheduled calls/flows HANG UP as soon as phone is picked up.

### ISSUE THREAD

**Issue by tonypearl** [chadsmith/OpenVBX-Plugin-Outbound#1]
Hello Chad,

You're brilliant, man, but I'm still having problems with your Outbound & Subscriptions plugins
with respect to the fact that whenever I set up a SCHEDULED CALL FLOW - either from
the 'Subscriptions-->Schedule Update' 
OR the 'Outbound-->Schedule Flow' functions, 
the phone rings, and then hangs up on me as soon as I pick up the phone.

I just upgraded to the new OpenVBX • v1.1.3 r64,
BUT was having the exact same problem on the 1.1.2 version.

FYI, when I click on the 'Debugger' tab in OpenVBX, it gives me this message:
ERROR    11100: Invalid URL format

When I click on the 'More Detail' link to the right of that message, it takes me to a Twilio page w/ a 
'404 Not Found' message.

Upon further investigation, I find that I get THIS message:
"The specified url
http://twiml/start/voice/8
is invalid."

NOTE: When I set up scheduled SMS flows, they work great!!
NOTE: When I click on 'Start Flow' & send the Flow out IMMEDIATELY, it works perfectly,
whether I'm sending it to just ONE number OR to a subscription list.

SO - it only screws up when sending it out via a SCHEDULED UPDATE!
wtf?  Why? 
PLEASE help!
I'm probably missing something simple that only YOU can see w/ your expert eyes.

Thank you very, very much & I look forward to hearing back from you soon.
Please don't leave me hanging!  

Best,
Tony

**Comment by tonypearl** [comment]
Hello?
Is anyone here?

I've been driving myself NUTS with this problem.
I've tried everything to get it resolved, but NO luck so far.

Every time I SCHEDULE a flow (Schedule Update or Schedule Flow),
the freaking phone HANGS UP on me and I get the error messages listed above.

Chad - are you on vacation or something?

I've tried uninstalling & reinstalling the plugins. Nope.
I've removed the 'timing' plugin. The problem still exists.

Please help.

I'm gonna hit you up on Twitter, bro!

Hope to hear from you soon,
Tony

**Comment by Gipetto** [comment]
Tony & Chad

What's happening on my machine is that `$config['base_url']` parameter isn't being properly set because the request is made directly to the plugin file instead of to OpenVBX. The need to do this is a deficiency in the abilities that OpenVBX provides to developers, not in how this plugin was developed.

The plugin might need to store some extra data to ensure that no matter how its invoked that it properly has the correct base url for the site. I'm not sure right now what the best answer to this problem is.

You can get some temporary relief by manually editing your `OpenVBX/config/config.php` file. Add a new item near the bottom of the file to be:

```
$config['base_url'] = 'http://your-domain.com/';
```

Note the trailing slash on the url. Also, if you're running out of a subdirectory be sure that the subdirectory name is in the url as well. A good way to guage what you need to enter there is to copy the url when on the Settings page, remove the last portion that says `settings/site` and then use that as the value for the 'base_url'.

**Comment by tonypearl** [comment]
Shawn,

IT WORKED!!
IT WORKED!!

You're my new hero, mate!

At first, I thought you were just ignoring my request,
but then, today...BAM!
You hit me out of left field & provide the solution
(even though it's temporary).

I'm actually quite surprised that no one else has ever mentioned this
problem before.

...And I hope that you geniuses are able to get this sorted out on a
more permanent level with the next update!

Slowly, but surely, this is all coming together quite nicely.

Thanks for all your help.

But don't be surprised if I bother you about something else soon, lol

--Tony

P.S.  And just because it's essential to be as specific as possible,
here's where I placed the line of code you gave me in the config.php file,
as shown within the context of the last few lines of code there:

*/
$config['proxy_ips'] = '';

 $config['base_url'] = 'http://MY-DOMAIN.com/OpenVBX-Directory/';

/*
|--------------------------------------------------------------------------
| Local config overrides
|--------------------------------------------------------------------------
|
| Sometimes your local environment just needs some things to be overridden
|
*/
if (is_file(APPPATH.'config/config-local.php')) {
include_once(APPPATH.'config/config-local.php');

}

/\* End of file config.php _/
/_ Location: ./system/application/config/config.php */

On Fri, Dec 2, 2011 at 6:21 PM, Shawn Parker <
reply@reply.github.com

**Comment by Gipetto** [comment]
Tony,

Glad to hear it worked.

Server configurations between hosts vary WILDLY. Its actually easier than you'd think for something like this to go unnoticed.

**Comment by dasilvatek** [comment]
Relieved to find this thread, since I've been at it for 2 days trying to figure out why scheduled outbound calls were clacking.

But his is a huge pain in the butt for anyone implementing several OpenVBX systems.

Any chance we will see these plugins ironed out and included in the standard build?

**Comment by chadsmith** [comment]
I pushed an update that saves the full URL of the flow rather than the flow ID. This will allow the cron to run from CLI without needing $config['base_url'].
