### ISSUE TITLE
Outbound Problem

### ISSUE THREAD

**Issue by juniortifo** [chadsmith/OpenVBX-Plugin-Outbound#9]
When I Schedule a text message with a list of 850 users after 220-240 message sending stop

But if I split my list of 850 users in 4 lists
all SMS message will be send

I don't understand why

I install a new openvbx on my second server and i have the same problem.

**Comment by minaevd** [comment]
Hi, did you get any error messages in your web server logs? Did you check error messages in Twilio? Do you think it's a plugin related issue or e.g. carriers are blocking you as a spammer?

--
Dmitry, CEO of Verbery

**Comment by juniortifo** [comment]
[01-Dec-2016 14:35:01 America/New_York] PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'The message body exceeds the 160 character limit.' in /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php:305
Stack trace:
#0 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php(229): Services_Twilio->_processResponse(Array)
#1 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio/ListResource.php(92): Services_Twilio->createData('/2010-04-01/Acc...', Array)
#2 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio/Rest/SmsMessages.php(16): Services_Twilio_ListResource->_create(Array)
#3 /home/messageriesms/public_html/www_gestion/plugins/OPENVBX-Output/queue.php(14): Services_Twilio_Rest_SmsMessages->create('+18198053109', '+14182099411', 'Festival Wester...')
#4 /home/messageriesms/public_html/www_gestion/OpenVBX/controllers/hook.php(48): require('/home/messageri...')
#5 [internal function]: Hook->index('outbound', 'cron')
#6 /home/messag in /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php on line 305



No error message in twilio account 
Merci

Junior Tifo Consultant
819-668-1073

**Comment by minaevd** [comment]
The error message ("The message body exceeds the 160 character limit.") is pretty obvious but I don't think it's related to the original question you asked.

I think the original issue might be related to a timeout configured on your server. So when you execute a program for 850 contacts it takes more than your configured threshold. Checkout your php environment variables and web server configuration.

--
Dmitry, CEO of Verbery

**Comment by juniortifo** [comment]
Sorry for my delay

i sended you my PHP setup 





info@juniortifo.com
819 668-1073

**Comment by juniortifo** [comment]
i see your post on GitHub

i have the same problems

Outbound Scheduling Problem #10


my cron job not working !!!

i have this error

[05-Jul-2017 18:20:03 America/New_York] PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'The message body exceeds the 160 character limit.' in /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php:305
Stack trace:
#0 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php(229): Services_Twilio->_processResponse(Array)
#1 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio/ListResource.php(92): Services_Twilio->createData('/2010-04-01/Acc...', Array)
#2 /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio/Rest/SmsMessages.php(16): Services_Twilio_ListResource->_create(Array)
#3 /home/messageriesms/public_html/www_gestion/plugins/OPENVBX-Output/queue.php(14): Services_Twilio_Rest_SmsMessages->create('+18198050923', '+18733785118', 'CLUB AGOSTINOS\n...')
#4 /home/messageriesms/public_html/www_gestion/OpenVBX/controllers/hook.php(48): require('/home/messageri...')
#5 [internal function]: Hook->index('outbound', 'cron')
#6 /home/messa in /home/messageriesms/public_html/www_gestion/OpenVBX/libraries/Services/Twilio.php on line 305

**Comment by juniortifo** [comment]
i rewrite my message under 160 characters and its working

how to modify openvbx to outbound message over 160 characters



Merci

Cellulaire: 819 668-1073
Courriel: info@juniortifo.com <mailto:info@juniortifo.com>

271 Ste-Marie, St-Boniface QC G0X2L0
